name: Web CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/web-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/web-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            apps/web/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint (web)
        run: pnpm --filter web lint

      - name: Typecheck (web)
        run: pnpm --filter web typecheck

      - name: Build (web)
        run: pnpm --filter web build

      - name: Unit tests (web)
        run: pnpm --filter web test
